### ISSUE TITLE
Adapt it to Odroid U3?

### ISSUE THREAD

**Issue by nickhuan** [answer17/lidarLite#2]
Hi,

Thanks for providing the interface. Can I call it a driver?

I'm using lidarlite for Odroid U3. May I know what need to be changed for Odroid U3?

Thanks

**Comment by nickhuan** [comment]
I've found out the thing needed to change for Odroid U3. In the function wiringPiI2CSetup in wiringPiI2C.c of the wiringPi library, the model is detected to get the device name for i2c. Well, the piBoardId function in wiringPi.c doesn't detect model for Odroid U3 ( the last 4 character in the string is 0000). Thus, I just assigned "/dev/i2c-4" to device and it should work for Odroid U3.

**Comment by answer17** [comment]
Just saw this.  Glad to hear you resolved it.

**Comment by nickhuan** [comment]
Hi answer 17, 
I keep on receiving "signal overflow" and sometimes "reference overflow". Do you know why? 

And do you know what are the differences between for register - internal and register-external? (aka, why to you use 0x47 to check status instead of 0x01).

Thanks a lot
